version: '3.8'

services:
    backend:
        build:
            context: ./phpConf
            dockerfile: Dockerfile
        ports:
            - '1234:80'
        volumes:
            - ./app:/var/www/html
        restart: always

    frontend:
        build:
            context: ./reactConf
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/project
        command: npm start

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
